# Generated by Django 5.2.4 on 2025-07-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editors',
                'ordering': ['name'],
                'permissions': [('can_vew', 'can_create'), ('can_edit', 'can_delete')],
            },
        ),
    ]
