# Generated by Django 5.2.4 on 2025-07-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_alter_book_options_alter_book_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book',
            new_name='books',
        ),
    ]
