# Generated by Django 5.2.4 on 2025-07-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_rename_book_library_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='library_name',
            new_name='name',
        ),
    ]
