# Generated by Django 5.2.4 on 2025-07-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_rename_name_library_library_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.author'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='library',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='book',
            field=models.ManyToManyField(to='relationship_app.book'),
        ),
    ]
