# Generated by Django 5.2.4 on 2025-07-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_author_alter_librarian_library_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'books'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
